/*
 * Copyright 2010-2013 JetBrains s.r.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.jetbrains.jet.j2k.test.update

import java.io.File

import org.jetbrains.jet.j2k.test.FAILED_TEST_DATA_EXTENSION

/**
 * Updates expected test data for converter tests according to current behaviour. (converter tests should pass after running the script)
 * Use this script if you change other subsystem (for example: formatting) and tests for converter fail.
 * Please check that changes in test data are relevant to your change so that no bugs are introduced silently.
 *
 * NOTE: script depends on existence of temporary files generated by running converter tests.
 */
fun main(args: Array<String>) {
    File("j2k/tests/testData").recurse {
        file ->
        val path = file.getAbsolutePath()
        if (path.endsWith(FAILED_TEST_DATA_EXTENSION)) {
            val targetFile = File(path.substring(0, path.length - FAILED_TEST_DATA_EXTENSION.length))
            if (targetFile.delete()) {
                if (file.renameTo(targetFile)) {
                    println("Replaced ${targetFile.getAbsolutePath()}")
                }
                else {
                    println("Failed to rename ${file.getAbsolutePath()} to ${targetFile.getAbsolutePath()}")
                }
            }
            else {
                println("Failed to delete ${targetFile.getAbsolutePath()}")
            }
        }
    }
}